Z-P0P/ZPOP

.gitignore
src/main/java/com/zpop/web/controller/LoginController.java
src/main/java/com/zpop/web/controller/LogoutController.java
src/main/java/com/zpop/web/service/KakaoLoginService.java
src/main/java/com/zpop/web/service/LoginService.java
src/main/java/com/zpop/web/service/NaverLoginService.java
src/main/java/com/zpop/web/service/TokenResponse.java
src/main/resources/application.properties
src/main/resources/static/css/button.css
src/main/resources/static/js/member/login.js

1. 소셜 로그인 기능을 추가하였습니다.
2. 로그아웃 기능은 추후 구현 예정입니다.
3. #9 확인부탁드려요.
4. 해당 PR은 화면 구현 안되어있습니다. 화면은 feature/header-layout쪽과 같이 확인부탁드려요.

feat: 카카오/네이버 소셜 로그인 기능 추가

---

src/main/java/com/zpop/web/entity/AgeRange.java
src/main/java/com/zpop/web/entity/Category.java
src/main/java/com/zpop/web/entity/ContactType.java
src/main/java/com/zpop/web/entity/meeting/Meeting.java
src/main/resources/mapper/MeetingDaoMapper.xml
src/test/java/com/zpop/web/dao/MeetingDaoTest.java

* ERD 수정에 따른 엔티티, DaoMapper 수정

fix : entities, dao related to Meeting

---

src/main/resources/static/js/comment/comment.js
src/main/resources/static/js/comment/reply.js
src/main/resources/templates/meeting/detail2.html

- 특정 엘리먼트에 event handler가 여러번 부착되는 버그를 수정

fix: add reply

---

src/main/java/com/zpop/web/controller/TempMeetingController.java
src/main/java/com/zpop/web/dao/MeetingDao.java
src/main/java/com/zpop/web/entity/meeting/Meeting.java
src/main/java/com/zpop/web/service/DefaultMeetingService.java
src/main/java/com/zpop/web/service/MeetingService.java
src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java

- 주최자의 모임 마감하기 구현
- 주최자의 모임 마감하기 테스트 코드 작성

feat: close meeting

---

src/main/java/com/zpop/web/entity/meeting/AdminMeetingView.java
src/main/resources/static/js/comment/comment.js
src/main/resources/static/js/comment/reply.js
src/main/resources/templates/meeting/detail2.html

- fetch 함수 인자로 URL에 hostname이 들어가있어서 제거하여 CORS에러 해결.

fix: reply cors

---

src/main/java/com/zpop/web/controller/TempMeetingController.java
src/main/java/com/zpop/web/dao/ParticipationDao.java
src/main/java/com/zpop/web/entity/Participation.java
src/main/java/com/zpop/web/service/DefaultMeetingService.java
src/main/java/com/zpop/web/service/MeetingService.java
src/main/resources/mapper/MeetingDaoMapper.xml
src/main/resources/mapper/ParticipationDaoMapper.xml
src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java

- 모임 참여자 내보내기 구현
- 화면, 참여하기, 취소하기 기능 및 화면이 완벽히 구현된게 아니라서 테스트 코드로 검증 완료
- `ParticipationDao` 인터페이스 정리 필요
- 모임 참여 취소하기 구현되면 내보내기에 반영 필요

feat: kick participant

---

src/main/java/com/zpop/web/controller/CommentController.java
src/main/java/com/zpop/web/dao/MeetingDao.java
src/main/java/com/zpop/web/service/DefaultMeetingService.java
src/main/resources/mapper/MeetingDaoMapper.xml
src/main/resources/mapper/ParticipationDaoMapper.xml
src/main/resources/static/js/comment/comment.js

fix: comment

---

pom.xml
src/main/java/com/zpop/web/controller/LoginController.java
src/main/java/com/zpop/web/controller/RegisterController.java
src/main/java/com/zpop/web/security/SecurityConfig.java
src/main/java/com/zpop/web/security/UserRole.java
src/main/java/com/zpop/web/security/UserSecurityService.java
src/main/java/com/zpop/web/security/ZpopUserDetails.java
src/main/resources/static/js/header.js
src/main/resources/static/js/member/register.js
src/main/resources/templates/inc/header.html
src/main/resources/templates/inc/layout.html
src/main/resources/templates/register.html

- 스프링 시큐리티 의존성 추가
- rest api 소셜 로그인 이후 수동 SecurityContext 인증 적용
- 닉네임 설정 이후 수동 SecurityContext 인증 적용
- 모임 상세화면에서 헤더 바뀌게 수정
- 모든 컨트롤러에 `session` -> 시큐리티로 수정 필요
- 시큐리티 설정 `authorizeHttpRequests`에 빠진 매핑 확인 필요

chore: spring security

---

src/main/java/com/zpop/web/service/DefaultMeetingService.java
src/main/java/com/zpop/web/service/MeetingService.java
src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java

- 모임 참여 취소 구현
- service 테스트 코드 작성후 확인 완료
- DAO 작성 필요
- merge nono !!

feat: cancel participation

---

src/main/resources/static/js/meeting/list/on-click-category.js
src/main/resources/static/js/meeting/list/on-click-region.js
src/main/resources/static/js/meeting/list/on-click-toggle.js

- 모임 리스트 조회시 결과가 없을 때 "찾고있는 모임이 없네요!" 요소 안보이던 버그 수정

fix: 모임 조회 페이지 조회 결과 없을 때 버그 수정

---

src/main/java/com/zpop/web/service/MeetingService.java

- interface MeetingService 작업한 메서드에 대한 주석 설명 추가

comment: meetings

---

src/main/java/com/zpop/web/controller/MeetingController.java
src/main/java/com/zpop/web/service/DefaultMeetingService.java
src/main/java/com/zpop/web/service/MeetingService.java

- 모임 연락처 얻기 API
테스트 코드는 시간 관계상 생략 😷

feat: get meeting contact

---

src/main/java/com/zpop/web/security/SecurityConfig.java
src/main/java/com/zpop/web/security/ZpopAuthenticationEntryPoint.java

미로그인 상태에서 `/member/me` 같은 인증이 필요한 페이지를 요청하면 시큐리티 때문에 whitelabel가 나옴

feat : 403 whitelabel 대신 로그인 alert로 수정

---

src/main/resources/static/js/member/notification.js
src/main/resources/templates/inc/header.html
src/main/resources/templates/inc/layout.html

fix : notification logout bug fixed

---

src/main/java/com/zpop/web/dao/MeetingDao.java
src/main/java/com/zpop/web/service/DefaultCommentService.java
src/main/resources/mapper/MeetingDaoMapper.xml

- 댓글, 답글 등록시 모임 commentCount 증가 구현

feat: increase comment count

---

src/main/java/com/zpop/web/controller/LoginController.java
src/main/java/com/zpop/web/controller/NotificationController.java
src/main/java/com/zpop/web/service/DefaultCommentService.java
src/main/resources/static/js/member/notification.js

feat : participation notification bug fixed

---

src/main/resources/static/css/member/component/notification-modal.css

Fix : notification modal css class names changed

---

src/main/java/com/zpop/web/controller/CommentController.java
src/main/java/com/zpop/web/service/CommentService.java
src/main/java/com/zpop/web/service/DefaultCommentService.java

- 댓글 수정, 삭제에 시큐리티 추가
- 댓글 수정, 삭제에 예외 로직 추가

fix: 댓글 수정, 삭제에 시큐리티 반영 및 로직 예외 추가

---

src/main/java/com/zpop/web/dao/MeetingDao.java
src/main/java/com/zpop/web/service/DefaultCommentService.java
src/main/resources/mapper/MeetingDaoMapper.xml

feat: 댓글 삭제시 모임 댓글 수 감소 

---

src/main/java/com/zpop/web/controller/ReportController.java
src/main/java/com/zpop/web/dao/ReportedMeetingDao.java
src/main/java/com/zpop/web/service/DefaultReportService.java
src/main/java/com/zpop/web/service/ReportService.java
src/main/resources/mapper/ReportedMeetingDaoMapper.xml
src/main/resources/static/css/member/component/report-modal.css
src/main/resources/static/js/meeting/report.js
src/main/resources/static/js/member/notification.js
src/main/resources/templates/meeting/detail.html

feat : block duplicated reports

---

src/main/java/com/zpop/web/controller/ReplyController.java
src/main/resources/static/js/comment/comment.js
src/main/resources/static/js/meeting/detail.js
src/main/resources/templates/meeting/detail.html

- 비로그인상태에서 detail page 버튼 접근을 제한함
- 댓글부분의 버튼들도 제한했으나 답글을 보는 기능까지 제한됨(추후 수정 예정)

refactor: block anonymous access to buttons of detail page

---

src/main/resources/static/css/member/meeting/list.css
src/main/resources/static/js/meeting/list/banner.js

- 베너 오른쪽 버튼을 여러번 클릭하는 경우 계속해서 베너가 넘어가서 흰색바탕만 나오는 현상이 있었음. 해당 버그 수정함
- 현재 인덱스를 확인해서 적정 수준 이상이면 배너가 동작하지 않도록 수정

[MINOR BUG FIX] 배너 우측버튼 클릭 시 계속해서 넘어가는 현상 수정

---

src/main/resources/static/js/member/notification.js
src/main/resources/templates/meeting/test.html

fetch URL에서 Host명 제거하여 CORS 에러 방지

fix: remove localhost:8080 from fetch URLs

---

src/main/resources/static/js/member/login.js

- 네이버 로그인 작동 안하는 이슈 해결 
- login.js 의 네이버로그인 로직부분 주석 제거

fix: naver login issue resolved

---

src/main/resources/static/js/comment/comment.js
src/main/resources/static/js/comment/edit-reply.js
src/main/resources/static/js/comment/reply.js

- 로그인상태와 비로그인상태에서 답글을 ajax로 뿌려주는 getReply()가 작동을 달리하게 함.

refactor: getReply bug

---

src/main/vue/src/components/modal/ServerError.vue
src/main/vue/src/utils/ServerException.js
src/main/vue/src/views/Layout.vue
src/main/vue/src/views/meeting/List.vue
src/main/vue/src/views/meeting/Search.vue

- 서버 에러 모달을 구현했습니다
- spring boot단 예외를 처리하기위한 커스텀 ServerException이옵니다
```js
export class ServerException extends Error {
/**
* fetch api를 이용한 요청중 예외가 발생했을때 사용하는 예외.
*
* @param {Response} res fetch api response
*/
constructor(res) {
super();
this.res = res;
}
}
```
res 값을 통해 status, message 등에 접근할 수 있습니다
예제는 디스코드 코드 채널에 정리했습니다

feat: 서버 에러 모달 구현

---

.gitignore
src/main/java/com/zpop/web/controller/MeetingController.java
src/main/vue/index.html
src/main/vue/src/api/meeting.js
src/main/vue/src/assets/css/component/select.css
src/main/vue/src/assets/css/deco.css
src/main/vue/src/assets/css/form.css
src/main/vue/src/components/header/Profile.vue
src/main/vue/src/components/meeting/MeetingFormDateInput.vue
src/main/vue/src/components/meeting/MeetingFormSelectInput.vue
src/main/vue/src/components/meeting/MeetingFormSelectTextInput.vue
src/main/vue/src/components/meeting/MeetingFormTextInput.vue
src/main/vue/src/components/meeting/SelectBox.vue
src/main/vue/src/components/modal/Default.vue
src/main/vue/src/utils/quill-generator.js
src/main/vue/src/utils/register.js
src/main/vue/src/views/meeting/Register.vue

- 게시글 작성 기능 추가했습니다.
- 이미지 업로드 시 콘솔에서 에러 발생하는 것 수정
- 모달 이벤트 버블링 기능 수정 
- Profile.vue 가 누락된 것 수정
- 기존에는 게시글 작성 후 업로드되는 기능이 없었음 (모임글 옵션 가져오는 것과 입력값 검증기능만 있었음)
- 기존 quill-generator.js 의 이미지 업로드 처리 로직에서, window.getSelection() 을 사용하는 부분이 있었는데, 코드가 잘못 기재되었음. 이로 인해 quill 에디터에서 이미지 업로드 시 콘솔에서 에러가 발생하고 이미지 업로드 후 커서가 이미지 다음으로 이동하지 않는 문제가 있었음.
- 모달 x 버튼을 누르면 이벤트가 wrapper DIV 태그에 전달되어서 closeModal 이벤트가 두번 발생했음
- Profile.vue 가 gitIgnore에 등록되어 있어서 Profile.vue가 누락되는 현상이 있었음
- 게시글 작성 추가
- 게시글 이미지 추가 시 에러 발생하는 것 제거 (이미지 추가하면 커서가 이미지 다음으로 이동하는 기능)
- 모달 x 버튼 영역에는 이벤트 제거 (제거해도 기존 function 으로 처리 가능함)
- Profile.vue 가 gitIgnore에 등록되어 있었던 문제 해결
- N/A

[FEAT,FIX] 게시글 작성 기능 & 모달 버그 수정 (이벤트 버블링)

---

src/main/vue/src/router/index.js
src/main/vue/src/views/404.vue

```js
...
path: "/",
component: () => import("@/views/Layout.vue"),
children: [
{
path: "/:pathMatch(.*)",
component: () => import("@/views/404.vue"),
},
...
```

feat: 404 views

---

src/main/vue/src/assets/css/meeting/thumbnail-list.css
src/main/vue/src/components/button/SoftToggle.vue
src/main/vue/src/components/button/Toggle.vue
src/main/vue/src/components/meeting/option-control/OptionControl.vue
src/main/vue/src/stores/meetingListStore.js

- 기본 토글, 쫄깃한 토글을 추가했습니다
- 모임을 토글 ONOFF로 모집 중 onoff 여부 구현했습니다

feat: 모임 리스트 조회 토글 옵션

---

src/main/java/com/zpop/web/security/SecurityConfig.java
src/main/java/com/zpop/web/security/UserSecurityService.java
src/main/java/com/zpop/web/security/ZpopUserDetails.java
src/main/vue/src/api/login.js
src/main/vue/src/components/header/Header.vue
src/main/vue/src/components/header/Profile.vue
src/main/vue/src/main.js
src/main/vue/src/router/index.js
src/main/vue/src/stores/memberStore.js
src/main/vue/src/views/meeting/Login.vue
src/main/vue/vite.config.js

- 로그아웃 기능이 추가되었음
- 로그인 버그 수정 (로그인을 해도 헤더의 표시정보가 바뀌지 않는 버그 수정)
- 로그아웃 기능이 리다이렉트로만 되어 있어서 rest api 적용이 필요했음
- 사용자 로그인 시 헤더의 표시정보가 바뀌지 않는 문제가 있었음
- java의 Spring Security 관련 정보 수정
- Header의 isMemberAuthenticated 관련 if conditional statement 수정
- 없음

[FEAT, FIX] 로그아웃 기능 추가 & 로그인 기능 버그 수정

---

src/main/vue/src/components/header/Header.vue
src/main/vue/src/components/modal/LoginModal.vue
src/main/vue/src/router/index.js
src/main/vue/src/stores/loginModalStore.js
src/main/vue/src/views/Layout.vue

* 인증필요 리다이렉트시 로그인 모달 띄우기 위해 로그인 모달Header에서 Layout으로 이동
* 인증필요 리다이렉트시 로그인 모달 보여지기 구현
ex: 로그인 안한 상태에서 모임 등록 페이지 이동 -> 로그인 모달 on -> 로그인 -> 로그인 모임 등록으로 리다이렉트
* 이를 구현하기 위해 로그인모달 상태 store 추가

feat: 로그인 리다이렉트, 로그인 모달 개선 구현

---

src/main/java/com/zpop/web/controller/NotificationController.java
src/main/resources/static/css/member/component/notification-modal.css
src/main/vue/src/components/header/NotificationModal.vue
src/main/vue/src/components/meeting/Participants.vue

participation.vue 에서 오타로 발생한 버그 수정
알림 모달 일부 수정

Participation.vue 에서 오타로 생긴 버그 수정

---

src/main/vue/src/components/meeting/option-control/OptionControl.vue
src/main/vue/src/views/meeting/Search.vue

- 검색 view에 토글 추가
- 메인 화면 토글 css 개선

Feat: 검색 toggle

---

src/main/vue/src/components/member/ProfileEdit.vue
src/main/vue/src/views/member/Edit.vue
src/main/vue/src/views/member/MyMeeting.vue
src/main/vue/src/views/member/Profile.vue

Feature: my profile edit

---

src/main/vue/src/components/comment/Comment.vue

원 댓글에 대한 답글을 누를때 인풋박스 안나타나는 버그 수정

fix: comment input box not showing bug

---

src/main/vue/src/components/comment/Comment.vue
src/main/vue/src/components/comment/InputBox.vue
src/main/vue/src/components/comment/Reply.vue
src/main/vue/src/components/comment/ReplyList.vue

- 소소한 버그 수정.
- 케밥을 제외한 댓글 부분 최종 완료.

fix: final fix for comment

---

src/main/java/com/zpop/web/controller/MeetingController.java
src/main/vue/src/api/meeting.js
src/main/vue/src/components/meeting/article/ControlModal.vue

- 모임 참여 후 모임 연락처 얻기 구현
- 모임 참여 리팩토링 -> 모임 참여후 조회수 증가 안함

feat: 모임 참여 후 모임 연락처 얻기

---

src/main/java/com/zpop/web/controller/admin/MeetingController.java
src/main/java/com/zpop/web/dao/CategoryDao.java
src/main/java/com/zpop/web/dao/RegionDao.java
src/main/java/com/zpop/web/dto/admin/AdminCategoryDto.java
src/main/java/com/zpop/web/dto/admin/AdminCategoryResponse.java
src/main/java/com/zpop/web/dto/admin/AdminMeetingDetailsDto.java
src/main/java/com/zpop/web/dto/admin/AdminMeetingDetailsResponse.java
src/main/java/com/zpop/web/dto/admin/AdminMeetingDto.java
src/main/java/com/zpop/web/dto/admin/AdminMeetingListResponse.java
src/main/java/com/zpop/web/dto/admin/AdminRegionResponse.java
src/main/java/com/zpop/web/service/admin/AdminMeetingService.java
src/main/java/com/zpop/web/service/admin/DefaultAdminMeetingService.java
src/main/resources/mapper/CategoryDaoMapper.xml
src/main/resources/mapper/RegionDaoMapper.xml
src/main/vue/src/components/admin/modal/AdminDetailModal.vue
src/main/vue/src/components/meeting/MeetingFormSelectInput.vue
src/main/vue/src/components/meeting/MeetingFormTextInput.vue
src/main/vue/src/utils/admin/meeting/AdminUpdateForm.js
src/main/vue/src/views/admin/meeting/Category.vue
src/main/vue/src/views/admin/meeting/List.vue
src/main/vue/src/views/admin/meeting/Meeting.vue
src/main/vue/src/views/admin/meeting/Region.vue

- 관리자 모임 관리 기능이 추가되었습니다.
- 세부 기능은 다음과 같습니다.
1) 모임글 관리기능 (모임글 삭제, 삭제취소)
2) 카테고리, 지역 관리 (카테고리, 지역 활성/비활성화)
- 기본적인 조회 기능은 있었으나, 세부 관리 기능은 누락되어 있었습니다.
- 검색어를 이용한 조회 및 각종 옵션을 통한 조회 기능은 빠져있었습니다.
- 롬복 적용 전이라 getter,setter가 일일히 구현되어 있었습니다.
- 모임글 관리 기능이 추가되었습니다. 추가된 기능은 다음과 같습니다.
1) 모임글 삭제 및 삭제취소 기능 (관리자가 모임글을 삭제하거나 삭제취소할 수 있습니다)
2) 모임글 조회 관련 기능 (검색어 및 옵션을 통해 모임글을 조회할 수 있습니다).
3) 카테고리, 지역관리 기능 (관리자가 카테고리, 지역을 활성화하거나 비활성화할 수 있습니다)
4) 롬복 적용하여 getter, setter 제거하였습니다.
- 다른 관리자 관련 PR을 합치지 않는다면 실제 동작하는 기능은 확인이 불가능할 수도 있습니다. 양해부탁드립니다.
- 검색어 관련 기능은 옵션 선택 기능이 조금 부족합니다. 추후 더 추가해야 할 것 같습니다.
- 카테고리, 지역 활성화는 체크버튼, 비활성화는 X 버튼인데 썩 직관적이지는 않은 것 같습니다. 의견있으시면 알려주세요.

[FEAT] 관리자 모임 관리 기능 추가 (모임글, 카테고리, 지역 관리)

---

src/main/vue/src/views/meeting/List.vue
src/main/vue/src/views/meeting/Search.vue

- 모든 views 컴포넌트에서 on scroll event가 발생 (모임 썸네일 리스트 요청)하길래 fix 함
```js
document.addEventListener("scroll", onScrollDown);
```
```js
document.addEventListener("scroll", onScrollDown);
onUnmounted(() => {
document.removeEventListener("scroll", onScrollDown);
})

fix: 모든 컴포넌트 views에서 scroll event 발생

---

src/main/java/com/zpop/web/controller/MeetingController.java
src/main/java/com/zpop/web/controller/admin/AuthController.java
src/main/java/com/zpop/web/dao/AdminDao.java
src/main/java/com/zpop/web/dto/admin/auth/AdminLoginDto.java
src/main/java/com/zpop/web/dto/admin/auth/AdminResponse.java
src/main/java/com/zpop/web/entity/Admin.java
src/main/java/com/zpop/web/global/exception/CustomException.java
src/main/java/com/zpop/web/global/exception/ExceptionHandlerRestControllerAdvice.java
src/main/java/com/zpop/web/global/exception/ExceptionReason.java
src/main/java/com/zpop/web/global/exception/ExceptionResponseBody.java
src/main/java/com/zpop/web/security/SecurityConfig.java
src/main/java/com/zpop/web/security/UserSecurityService.java
src/main/java/com/zpop/web/security/ZpopUserDetails.java
src/main/resources/mapper/AdminDaoMapper.xml
src/main/vue/src/api/admin/auth.js
src/main/vue/src/api/admin/index.js
src/main/vue/src/router/admin.js
src/main/vue/src/router/index.js
src/main/vue/src/stores/memberStore.js
src/main/vue/src/views/admin/Login.vue

[feat: exception handle](https://github.com/Z-P0P/ZPOP/commit/8f2f10978b71be4a00fac070287a58a37cb2569c)
- 예외처리 쉽게하기위해 추가했습니다
- `enum ExceptionReason`에 에러 종류를 추가 하신 후
```java
@Getter
public enum ExceptionReason {
// 400
YOUR_ERROR(BAD_REQUEST, "내가 만든 커스텀 에러"),
// 또는
// 404
NOT_FOUND_MEMBER(NOT_FOUND, "존재하지 않는 사용자입니다");
private final HttpStatus httpStatus;
private final String message;
ExceptionReason(HttpStatus httpStatus, String message) {
this.httpStatus = httpStatus;
this.message = message;
}
}
```
- 다음과 같이 사용하시면 됩니다
```java
throw new CustomException(ExceptionReason.YOUR_ERROR);
throw new CustomException(ExceptionReason.NOT_FOUND_MEMBER);
```
[feat: implements admin login with security](https://github.com/Z-P0P/ZPOP/commit/e4e83757d7008e922e28ea51150e4a4a86c4474d)
- 어드민 페이지 접속하려면 로그인이 …

feat: 어드민 로그인 및 백엔드 전역 예외관리

---

src/main/vue/src/components/meeting/option-control/Region.vue

fix: Region css

---

src/main/vue/src/api/comment.js
src/main/vue/src/components/comment/Comment.vue
src/main/vue/src/components/comment/CommentModal.vue
src/main/vue/src/components/comment/SelectModal.vue
src/main/vue/src/components/meeting/article/Article.vue

- 댓글 케밥메뉴 중 일단 삭제를 구현해봄. 1차때와는 달리 select.js를 쓸 수가 없어서 셀렉트모달이 자동으로 반응(사라짐)이 안되고 있는데 향후 경환님과 의논하여 개선해야함.

feat: comment kebob delete

---

src/main/java/com/zpop/web/controller/MeetingController.java
src/main/java/com/zpop/web/dto/ParticipationResponse.java
src/main/java/com/zpop/web/global/exception/ExceptionReason.java
src/main/java/com/zpop/web/service/DefaultMeetingService.java
src/main/java/com/zpop/web/service/MeetingService.java
src/main/vue/src/components/meeting/article/Article.vue
src/main/vue/src/components/meeting/article/ControlModal.vue

- MeetingService participate 모든 예외 CustomException으로 수정
- ExceptionReason에 모임과 관련된 예외 추가
- 모임 참여 후 마감되었다면 `모집마감`으로 UI 버튼 수정
- 마감된 모임은 참여취소 불가능하게 수정

refactor: 모임 참여하기

---

src/main/vue/src/components/meeting/article/Article.vue

- 모임 주최자, 참여자, 일반 role에 따라 select modal이 다르게 보이게 구현 함

feat: 모임 조회 셀렉트 모달에 role 적용

---

src/main/java/com/zpop/web/controller/MemberController.java
src/main/resources/static/css/member/member/profile-modal.css
src/main/vue/src/api/index.js
src/main/vue/src/api/member.js
src/main/vue/src/api/report.js
src/main/vue/src/assets/css/meeting/component/report-modal.css
src/main/vue/src/components/meeting/Participant.vue
src/main/vue/src/components/meeting/ParticipantList.vue
src/main/vue/src/components/meeting/UserProfile.vue
src/main/vue/src/views/admin/meeting/List.vue
src/main/vue/src/views/meeting/Detail.vue

feat participationlist and UserProfile

---

src/main/java/com/zpop/web/controller/LoginController.java
src/main/vue/src/components/header/Header.vue
src/main/vue/src/components/header/NotificationModal.vue

fix: 알림 경로 수정

---

src/main/java/com/zpop/web/controller/ReportController.java
src/main/vue/src/components/meeting/UserProfile.vue
src/main/vue/src/components/member/ReportUser.vue

feat : report modal

---

src/main/java/com/zpop/web/controller/LoginController.java
src/main/vue/src/assets/css/meeting/article.css
src/main/vue/src/components/meeting/Participants.vue
src/main/vue/src/components/meeting/article/ControlModal.vue
src/main/vue/src/components/member/MyProfile.vue
src/main/vue/src/components/member/ProfileEdit.vue
src/main/vue/src/components/modal/Default.vue
src/main/vue/src/views/member/Profile.vue

- Default Modal의 css를 개선하였습니다.
- Detail page의 css를 개선하였습니다.
- 기존 pinia 🍍 store에 member의 fame이 undefined되는 현상을 해결 (login controller에 해당 코드 추가)
- +내 프로필 페이지에서 pinia store를 사용하는 것으로 변경하였습니다.
- 참고할 이슈가 있다던가, 추가 코멘트를 적어주세요 !
#133

fix:modal. css , detail-page css, userStore apply to my page

---

src/main/java/com/zpop/web/utils/ElapsedTimeCalculator.java
src/main/vue/src/api/comment.js
src/main/vue/src/components/comment/Comment.vue
src/main/vue/src/components/comment/CommentList.vue
src/main/vue/src/components/comment/CommentModal.vue
src/main/vue/src/components/comment/InputBox.vue
src/main/vue/src/components/comment/ReplyList.vue
src/main/vue/src/components/comment/SelectModal.vue
src/main/vue/src/stores/commentStore.js
src/main/vue/src/stores/meetingDetailStore.js
src/main/vue/src/stores/replyStore.js
src/main/vue/src/views/meeting/Detail.vue

- 댓글 케밥 여러개 동시에 뜨지 않도록 로직 구현 (하나 열리면 다른 것들 닫힘)
-  댓글 케밥에서 삭제시 실시간으로 댓글 리스트에서 삭제 구현 (AJAX)
- 댓글 등록시 상위의 컴포넌트에서 getDetail()을 호출하는 방법을 버리고 댓글 컴포넌트 내부에서 댓글 리스트 갱신구현하는 방식으로 변경 ==>  댓글을 달때마다 미팅디테일페이지 조회수 늘어나는 것 방지.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Feature/kebob  - 삭제기능 완성

---

src/main/java/com/zpop/web/controller/MeetingController.java
src/main/java/com/zpop/web/controller/TempMeetingController.java
src/main/java/com/zpop/web/global/exception/ExceptionReason.java
src/main/java/com/zpop/web/service/DefalutMemberService.java
src/main/java/com/zpop/web/service/DefaultMeetingService.java
src/main/vue/src/api/meeting.js
src/main/vue/src/components/meeting/article/Article.vue
src/main/vue/src/components/meeting/article/ControlModal.vue
src/main/vue/src/components/meeting/article/SelectModal.vue
src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java

를 구현했습니다
- `DefaultMeetingService.delete`에 커스텀예외를 적용했습니다
- 모임에 참여자가 있을 경우
- 삭제 정상

feat: 모임 삭제하기

---

src/main/vue/src/assets/css/meeting/article.css
src/main/vue/src/components/meeting/article/Article.vue
src/main/vue/src/components/meeting/option-control/Region.vue

- 퀼에디터로 작성한 모임글에 이미지를 추가하는 경우 이미지 크기가 클 때 상세보기 페이지 영역 밖으로 벗어나는 현상 수정
- Article.css에 scoped로 되어있는 부분 제거 (다른 pr에는 import된 css파일 main.js로 이동했습니다).
- 메인화면에서 지역카테고리선택 시 색상을 main color로 변경 (누락된 것 추가했습니다)

[FIX] 경미한 CSS 버그 수정

---

src/main/vue/src/components/PageLoader.vue
src/main/vue/src/utils/RegisterForm.js
src/main/vue/src/views/meeting/List.vue
src/main/vue/src/views/meeting/Register.vue

- CSS 로더 다른 것을 추가했습니다.
- 메인화면이나 기타 fetch요청하는 페이지에서 로딩 시간이 있어서 페이지 렌더링이 부자연스러운 문제가 있습니다. 보통 다른 SPA(Single Page Application) 사이트에서는 로딩화면을 두기도 하더라구요.
모임글 아래쪽에도 loader가 적용되어있으니 이상하면 알려주세요
그리고 전체화면으로 사용하고 싶으시면 해당 컴포넌트에 :isWholePage="true" 를 바인딩시켜주세요.

[FEAT] CSS loader 추가

---

src/main/java/com/zpop/web/controller/ReportController.java
src/main/java/com/zpop/web/dto/RequestMeetingReportDto.java
src/main/java/com/zpop/web/dto/RequestMemberReportDto.java
src/main/resources/static/css/member/component/report-modal.css
src/main/vue/src/api/report.js
src/main/vue/src/assets/css/meeting/component/report-modal.css
src/main/vue/src/components/meeting/article/Article.vue
src/main/vue/src/components/meeting/article/SelectModal.vue
src/main/vue/src/components/report/ReportCompleteModal.vue
src/main/vue/src/components/report/ReportMeeting.vue

article.vue 에 meetingReportModal.vue 컴퍼넌트 추가하였습니다.
-모임 신고 모달 뛰우기
-모임 신고하기
-중복 신고 예외 처리

Feat : 모임 신고 모달과 기능 구현, 중복 신고 예외 처리

---

src/main/vue/src/router/index.js

vue-router의 [scroll-behavior.html](https://router.vuejs.org/guide/advanced/scroll-behavior.html)를 이용하여
모든 view 이동시 스크롤 상단으로 이동하게 구현
resolve #197

feat: 모든 view 이동시 스크롤 상단 고정

---

src/main/vue/src/router/index.js
src/main/vue/src/views/LoginProc.vue
src/main/vue/src/views/meeting/Register.vue

- 로그인 시 새로추가된 로딩모달에 가려져서 로그인 모달이 안보이는 현상 수정
- 로그인 모달 transition 효과 추가
- 검색페이지 route에 name 추가 'searchMeeting'
- 모임글 작정 시 취소 버튼 기능 추가 (메인화면으로 이동)

[FIX] 로그인 모달 CSS 수정 및 기타 경미한 변경사항 작업 (route, 모임글 취소 기능)

---

src/main/vue/src/components/admin/SearchBar.vue
src/main/vue/src/components/header/Header.vue
src/main/vue/src/components/modal/SearchModal.vue

- 모바일 화면에서 검색모달 추가됨 (기존 찬우님 작업) 
=> vue로 옮김
- 지역선택 옵션, 모임글 카테고리 선택 옵션은 있었으면 좋을 것 같네요.

[FEAT] 모바일 모임글 검색 기능 추가

---

src/main/vue/src/components/meeting/ScrollUpBtn.vue
src/main/vue/src/views/meeting/List.vue

- 에니메이션 적용을 위해 svg 파일을 css의 background로 사용하는 것이 아닌 tag로 변경했습니다.
- 기존에는 에니메이션이 없었습니다.
- css background 속성을 이용해서 버튼의 모양을 불러왔습니다.
- 스크롤 상단으로 이동하는 버튼을 hover 했을 때 적용되는 에니메이션이 추가되었습니다.
- 에니메이션 적용을 위해 컴포넌트 내부에 svg 태그를 사용했습니다.
- 에니메이션 개선 사항이 있으면 알려주세요.

[REFACTOR] 스크롤 상단 이동 animation 추가 및 기타 컴포넌트 개선

---

src/main/java/com/zpop/web/controller/LoginController.java
src/main/java/com/zpop/web/controller/NotificationController.java
src/main/java/com/zpop/web/dao/NotificationDao.java
src/main/java/com/zpop/web/service/DefaultCommentService.java
src/main/java/com/zpop/web/service/DefaultMeetingService.java
src/main/resources/mapper/NotificationDaoMapper.xml
src/main/vue/src/api/notification.js
src/main/vue/src/components/header/NotificationModal.vue

-알림 순서가 오래된것부터 보였었는데 이제 최신 순서로 보입니다
-평가하지 않은 모임이 있어요 알림 버그 수정하였습니다.

feat : notification 모달 버그 수정, 알림 순서 정렬

---

src/main/java/com/zpop/web/controller/ReportController.java
src/main/vue/src/api/report.js
src/main/vue/src/assets/css/meeting/component/report-modal.css
src/main/vue/src/components/comment/SelectModal.vue
src/main/vue/src/components/report/ReportComment.vue

댓글 신고 모달 뛰우기 및 신고하기
같은 댓글 중복 신고는 못하게 처리하였습니다

feat : 댓글 신고 기능 구현

---

src/main/vue/src/components/meeting/MemberProfile.vue

- 참여자 프로필 조회시 "내보내기" "신고하기" 렌더링 여부 구현입니다
- `<template>` 더 개선할 수 있을 것 같은데.. 일단 돌아가서 냅둡니다
- 다음 세 가지 모두 보려면 로그인이 필요합니다

feat: 참여자 프로필 조회시 "내보내기" "신고하기" 렌더링 여부

---

src/main/java/com/zpop/web/controller/LoginController.java
src/main/java/com/zpop/web/dao/ReportedMemberDao.java
src/main/java/com/zpop/web/dto/BlockedMemberDto.java
src/main/java/com/zpop/web/global/exception/CustomException.java
src/main/java/com/zpop/web/global/exception/ExceptionHandlerRestControllerAdvice.java
src/main/java/com/zpop/web/global/exception/ExceptionReason.java
src/main/java/com/zpop/web/service/KakaoLoginService.java
src/main/java/com/zpop/web/service/LoginService.java
src/main/java/com/zpop/web/service/NaverLoginService.java
src/main/resources/mapper/ReportedMemberDaoMapper.xml
src/main/vue/src/assets/css/component/modal.css
src/main/vue/src/assets/css/form.css
src/main/vue/src/assets/css/meeting/component/modal.css
src/main/vue/src/views/LoginProc.vue

- 관리자가 신고 관리화면에서 접수된 신고를 영구정지, 또는 정지 처리했을 때 해당 반영내용 (처분내용) 이 로그인 시 반영될 수 있도록 적용하였습니다.
- 사용자 정지기능은 있었으나, 사용자 로그인 시 해당 정지사항을 확인하는 로직이 없었음.
- CustomException에 ExceptionReason을 추가하는 것은 있었으나, 세부 내용 추가를 위한 details는 없었음
- 해당 기능 사용을 위해 DB에 view를 추가했습니다 (BlockedMember)
```sql
SELECT 
reportedView.reportedId,
reportedView.reportedType,
reportedView.blockedAt,
reportedView.releasedAt
FROM
(SELECT 
crt.type AS reportedType,
c.writerId AS reportedId,
rc.blockedAt AS blockedAt,
rc.releasedAt AS releasedAt
FROM
reportedComment rc
JOIN comment c ON rc.commentId = c.id
JOIN commentReportType crt ON crt.id = rc.typeId
WHERE
rc.blockedAt IS NOT NULL 
UNION 
SELECT 
mrt.type AS reportedType,
m.regMemberId AS reportedId,
rm.blockedAt AS blockedAt,
rm.releasedAt AS releasedAt
FROM
reportedMeeting rm
JOIN …
```

[FEAT] 정지된 사용자 로그인 차단기능

---

src/main/vue/src/components/comment/Comment.vue
src/main/vue/src/components/comment/Reply.vue

- 디테일 페이지내에서 비회원에게 kebob메뉴를 노출시킬지 여부에 대해 상단의 정책을 따르기로하여 댓글도 케밥을 노출시킴.
- 신고담당자는 신고메뉴 클릭시 로그인으로 전환처리.

refactor: unblock anonymous access to comment kebob

---

src/main/vue/src/views/404.vue
src/main/vue/src/views/meeting/Register.vue

fix: 모임 등록 view 버튼 css

---

src/main/vue/src/assets/css/meeting/component/report-modal.css
src/main/vue/src/components/comment/SelectModal.vue
src/main/vue/src/components/meeting/MemberProfile.vue
src/main/vue/src/components/meeting/ParticipantList.vue
src/main/vue/src/components/report/ReportUser.vue

모임 글 상세보기에서 참여자 신고를 구현하였습니다.
신고 모달 버튼 css 수정하였습니다.

feat : 사용자 신고 구현 및 css 수정

---

src/main/java/com/zpop/web/controller/LoginController.java
src/main/vue/src/assets/css/form.css
src/main/vue/src/views/meeting/List.vue

- 등록되지 않은 사용자가 처음 로그인 할 시 닉네임 설정 화면을 보여주는 부분이 동작하지 않는 문제가 있었고, 이 부분을 해결하였음
- 닉네임모달컴포넌트를 포함하고 있는 list.vue 에 import가 누락되어있었음
- LoginController 로직 순서가 맞지 않아 차단된 사용자를 먼저 확인하는 로직이 우선하여 예외가 발생하였음
- 상기 내용 수정

[FIX] 닉네임 설정화면이 표시되지 않는 버그 수정

---

src/main/vue/index.html
src/main/vue/src/components/PageLoader.vue
src/main/vue/src/components/admin/modal/AdminDetailModal.vue
src/main/vue/src/components/admin/modal/AdminModal.vue
src/main/vue/src/components/button/SoftToggle.vue
src/main/vue/src/components/comment/ReplyList.vue
src/main/vue/src/components/header/NotificationModal.vue
src/main/vue/src/components/meeting/Participant.vue
src/main/vue/src/components/meeting/option-control/SearchBar.vue
src/main/vue/src/components/modal/Changed.vue
src/main/vue/src/components/modal/Default.vue
src/main/vue/src/components/modal/Full.vue
src/main/vue/src/components/modal/ServerError.vue
src/main/vue/src/components/report/ReportCompleteModal.vue

- 누락된 파일들이 있어서 추가로 defineProps와 defineEmits 를 제거함.

[Cleanup] import에서 defineProps와 defineEmits제거 -2차분-

---

src/main/vue/src/api/meeting.js
src/main/vue/src/components/participant/MemberProfile.vue
src/main/vue/src/components/participant/ParticipantList.vue

- 참여자 내보내기를 구현했습니다
- 예외처리도 동일하게 모달에서 메세지를 표시해요

feat: 내보내기 vue 구현

---

src/main/vue/src/views/member/MyMeeting.vue

- 모임 평가후, 컴포넌트의 버튼이 `평가하기`에서 `평가완료`로 동적으로 바뀌는걸 구현

feat: 모임 평가후 컴포넌트 동적으로 변경

---

src/main/vue/src/views/member/MyMeeting.vue

- 모임 평가하기 클릭시, 참여자 수에 상관없이 `참여자가 없어요` 모달이 같이 뜨던 버그를 수정했습니다
- 주석 추가, 함수 분리 등 약간의 코드 리팩토링도 했습니다
- CSS 수정이 필요합니다

fix: 평가하기 클릭시, 무조건 참여자 없는 에러 뜨던 현상 수정

---

src/main/vue/src/assets/css/form.css
src/main/vue/src/views/admin/Home/Home.vue
src/main/vue/src/views/meeting/Register.vue

- 명진님 요청사항에 따라 form input 의 focus 색상을 true-blue => main-color로 변경하였음
- 관리자화면에서 일별 신규 회원수를 표시하는 차트의 label을 '모임 수' => '회원 수' 로 정정함

[FIX] 관리자화면 라인차트 라벨 오기재 사항 및 input tag의 focus 색상 변경

---

src/main/java/com/zpop/web/controller/MemberController.java
src/main/java/com/zpop/web/global/exception/ExceptionReason.java
src/main/java/com/zpop/web/service/DefalutMemberService.java
src/main/java/com/zpop/web/service/MemberService.java
src/main/vue/src/assets/css/member/mypage.css
src/main/vue/src/components/member/ProfileEdit.vue

- 회원 프로필 수정 구현입니다
- 로직을 많이 수정했습니다
- 기존
1 프로필 사진만 업로드 or 닉네임만 수정 or 프로필 사진 + 닉네임 변경 -> 3개의 분기를 나누어 모달로 처리한 상태
2 저장하기를 눌러야 분기에 따라 이미지 업로드 + 닉네임 update 요청이 갔음
- 수정후
1 이미지 업로드시 바로 이미지 업로드 요청
2 저장하기를 누르면 이미지 + 닉네임을 담아 같이 update 요청
3 모달은 두개로 줄임 (닉네임 변경 안내 확인 모달, 결과 모달)
추가로 사용자 입력 상태에 따라 버튼 클래스를 동적으로 바꾸긴했는데..
`watch`를 통해서 동작하는데 생각대로 잘 안되서 내일 논의후 빼는 쪽으로 진행하겠읍니다
```js
// 닉네임 입력 상태
const inputStatus = reactive({
inputMessage: "",
isNicknameValid: null,
inputNickname: "",
});
watch(
() => inputStatus.inputNickname,
() => {
if (inputStatus.inputNickname.length === 0) {
editState.nickname = false;
inputStatus.isNicknameValid = null;
inputStatus.inputNickname = "";
inputStatus.inputMessage = "";
}
}
);
// 닉네임, 이미지 변경 여부
const editState = reactive({
nickname: false,
image: false,
imageName: "",
}); …
```

feat: 회원 프로필 수정

---

src/main/vue/src/assets/css/member/rate.css
src/main/vue/src/components/member/ProfileEdit.vue
src/main/vue/src/components/modal/Changed.vue
src/main/vue/src/views/member/Edit.vue
src/main/vue/src/views/member/MyMeeting.vue
src/main/vue/src/views/member/Profile.vue

- vue단의 불필요한 코드 정리
- rate modal ,, 머지가 잘못되었나봐요 오류 수정했습니다.
- 피그마 보면서 최종적으로 css 다듬었습니다.
- #133

cleanup: 마이 페이지 코드 클린업 , 모달 오류

---

src/main/vue/src/assets/css/meeting/component/report-modal.css

Feature/report 신고 모달 textarea 폰트 색상 변경
