- src/main/java/com/zpop/web/controller/HomeController.java
- src/main/java/com/zpop/web/controller/MeetingController.java
- src/main/resources/static/css/member/component/meeting-info.css
- src/main/resources/templates/inc/select-modal.html
- src/main/resources/templates/meeting/detail-imple.html
1. 모임 상세보기의 케밥 모달 임시 구현.
추후 상세보기 페이지 요청되면 합치기
[refactor: meeting select modal](https://github.com/Z-P0P/ZPOP/commit/cdf9f68be357a9e0c2ba2fc7efa966f77cf24f2c)
2. 모임 상세보기의 제목 옆 케밥 아이콘에 cursor 옵션 추가
3. root 경로 -> 모임 리스트 forward 추가
> refactor: 모임 상세보기의 케밥 모달 임시 구현

- src/main/java/com/zpop/web/dao/ParticipationDao.java
- src/main/java/com/zpop/web/entity/Member.java
- src/main/java/com/zpop/web/service/DefaultMeetingService.java
- src/main/resources/mapper/ParticipationDaoMapper.xml
- src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java
- 참여자 강퇴에 TODO로 남겨둔 `강퇴할 참여자가 탈퇴한 회원인지 확인후, 탈퇴한 회원이라면 모임 취소 처리후 예외를 던진다` 추가
- 윗 내용 테스트 코드 추가
- 브랜치 병합중 삭제된 코드 복구
- Member Entity Date 타입 수정
> feat: 모임 참여자 강퇴하기에 탈퇴 회원 예외처리

- src/main/java/com/zpop/web/service/DefaultMeetingService.java
- src/main/resources/mapper/MeetingDaoMapper.xml
* 모임 조회에 startedAt 옵션 추가하여 응답. 모임시작 시간이 지났으나 마감처리되지 않은 글을 모집 완료로 응답하기 위해서 추가함
- 불필요 코드 삭제
- 모임 리스트 조회시 다음과 같은 문제가 있어서 수정
- 모임 시작 시간 `startedAt`이 지났으나, 마감 시간`closedAt`이 업데이트 되지 않아서
시작 시간이 지난 모임도 사용자에게 `모집중`으로 응답하고 있었음
```xml
<choose>
<when test="isClosed == false"> 
AND closedAt IS NULL
</when>
<when test="isClosed == true"> 
AND closedAt IS NOT NULL
</when>
</choose>
```
```java
if (m.getClosedAt() != null )
isClosedResult = true;
```
- SQL은 "마감여부"가 `false`라면, `closedAt`이 null이고, `startedAt`이 현재 시각보다 미래인 것을 조회
```xml
<choose>
<when test="isClosed == false">
AND closedAt IS NULL
<![CDATA[ AND startedAt >= NOW() ]]>
</when>
<when test="isClosed == true">
AND closedAt IS NOT NULL
</when>
</choose>
```
- 모임 시작시간이 지났으나 UPDATE 되지 않아 `closedAt`이 null인 데이터가 있을 수 있음.
- 따라서 가져온 view entity의 …
> refactor: 모임 리스트 조회 - 모임 시작 시간과 관련한 로직 수정

- src/main/resources/static/css/member/component/header.css
- src/main/resources/static/css/member/component/select.css
- src/main/resources/static/js/meeting/list/list.js
- src/main/resources/templates/inc/header.html
- 헤더 프로필 선택모달 클릭 시 해당 텍스트가 지역 옵션 선택한 것으로 들어가는 버그 수정함
- 헤더 프로필 선택모달 클릭 범위가 텍스트 영역으로 국한되는 문제 수정함
- 로그인 후 헤더 프로필 클릭 시 나타나는 선택창 모달 클릭 영역이 택스트로 국한되는 문제가 있었음
- 메인 모임글 조회 화면에서, 로그인 후 헤더 프로필 클릭 시 나타나는 선택창 모달 클릭 시 해당 내용이 지역카테고리 선택 아이콘으로 들어가는 버그가 있었음 
- 인라인 js 코드 삭제
- a태그 크기를 키워서 링크이동 가능하게 바꿈
- 이전에 보니 인라인 자바스크립트 코드로 해결을 한 것 같으나, 아무래도 a 태그 써먹는게 좋을 것 같아 수정함
(다른 페이지 헤더 보니 인라인 자바스크립트 코드 안들어가있어서 어쩄든 수정해야 했음)
- querySelector 수정
> fix: 헤더 셀렉트 모달 수정

- src/main/java/com/zpop/web/controller/MeetingController.java
- src/main/java/com/zpop/web/service/DefaultMeetingService.java
- src/main/java/com/zpop/web/service/MeetingService.java
- 모임 참여자 목록 얻기에 대한 개선
- 메서드에 대한 주석 추가
- `commentCount`를 DAO를 통해 조회하는게 아닌 `Meeting` 엔티티에서 commentCount getter를 사용하는 것으로 수정
> refactor: 모임 참여자 목록 얻기 개선

- src/main/resources/static/css/deco.css
- src/main/resources/templates/inc/meeting-detail-modal.html
- src/main/resources/templates/meeting/detail.html
- 모임 상세조회 view에서 모달, 버튼들이 겹쳐지는 문제를 해결 함
- deco.css에 다음 추가
```css
.z-idx-1 {
z-index: 100;
}
.z-idx-2 {
z-index: 200;
}
.z-idx-3 {
z-index: 300;
}
```
> fix: 모임 상세조회 모달 겹쳐지는 문제

- src/main/vue/src/App.vue
- src/main/vue/src/assets/css/meeting/thumbnail-list.css
- src/main/vue/src/components/header/header.vue
- src/main/vue/src/components/header/login-modal.vue
- src/main/vue/src/components/modal/Default.vue
- src/main/vue/src/router/index.js
- src/main/vue/src/views/Layout.vue
- src/main/vue/src/views/meeting/List.vue
- src/main/vue/src/views/meeting/Search.vue
기본 모달을 구현했습니다
톡방에 설명 해놓았으니 참고해주세요
추후 관리자 vue router까지 고려해서 수업 때 배운걸 반영했습니다
다른 컴포넌트(새로 만든 모달 컴포넌트)까지 CSS 영향받아서 적용했습니다.
모임 검색 구현했읍니다.
검색 결과가 없으면`(검색어) 검색결과` 가 중앙으로 줄어드는 CSS 이슈가 있읍니다
> feat: 기본 모달 & 검색

- src/main/java/com/zpop/web/controller/LoginController.java
- src/main/vue/src/stores/memberStore.js
- 로그인 이후 새 탭에서 다시 접속했을 때 로그인 상태가 유지되지 않는 문제 해결
- pinia-plugin-persist 을 사용해서 새로고침 시 로그인상태가 유지되는 것은 확인을 했음
- 그러나, 새 탭에서 주소 입력하여 들어갔을 때 로그인상태가 유지되지 않은 현상이 있었음
- pinia-plugin은 기본적으로 sessionStorage를 사용하는 것이기 때문에, 새 탭에서는 로그인이 유지되지 않는 것이 정상임
- pinia-plugin-persist를 사용하는 것이 크게 의미가 없는 것 같아서 사용하지 않는 것으로 변경
- 최초 로그인 시 sessionStorage에 직접 로그인 정보 저장 (닉네임, 프로필정보) -> 저장되는 이름은 ('ZPOP_MEMBER_INFO')
- 처음 사이트에 접속했을 때 sessionStorage 정보를 확인하고, null이면 서버에 userDetail 정보를 요청
- userDetail에 정보가 있으면 이를 sessionStorage에 저장하고, 헤더 정보를 갱신함
- N/A
> fix: 기존 탭에서 로그인한 상태에서 새 탭으로 접속 시 로그인 정보가 유지되지 않는 문제 해결

- src/main/vue/src/components/meeting/SelectBox.vue
- src/main/vue/src/components/meeting/option-control/OptionControl.vue
- src/main/vue/src/components/meeting/option-control/Region.vue
- src/main/vue/src/stores/meetingListStore.js
- src/main/vue/src/views/meeting/List.vue
- 1차 프로젝트에서  찬우님이 구현하였던 지역옵션 선택을 통한 모임글 조회 기능을 추가하였습니다.
- 모임글 조회 시 지역옵션을 선택하여 추가하는 기능이 vue로 구현되어있지 않았음
- 지역옵션을 선택하여 선별적으로 조회하는 기능을 추가하였음
- 지역옵션 선택에 대한 로직은 다음과 같습니다.
1. 지역 옵션을 선택하면 오른쪽에 파란색 아이콘으로 누적해서 옵션이 선택됨
2. 누적은 3개까지 가능하고, 3개인 상태에서 지역옵션을 새로 선택하는 경우 가장 마지막에 있는 지역옵션을 제거하고 추가함
3. 이미 존재하는 지역명을 다시 클릭하는 경우 해당 선택된 내역이 삭제됨
- X아이콘 image 요청이 매번 발생하고, 이로 인해서 이미지 로딩시간이 있는데, 기존에 다운받은 이미지를 왜 재요청하는지 모르겠습니다.
> [FEAT] 메인의 모임글 조회 화면에서 지역 옵션을 선택하는 기능 추가

- src/main/java/com/zpop/web/dto/MeetingDetailResponse.java
- src/main/vue/src/assets/css/meeting/article.css
- src/main/vue/src/components/button/Round.vue
- src/main/vue/src/components/button/RoundDisabled.vue
- src/main/vue/src/components/meeting/Article.vue
- src/main/vue/src/views/meeting/Detail.vue
- article.css 버튼에 먹혀있던 main-color, grey 색을 뺐습니다. 대신 btn-dead, btn-action 클래스를 추가하여 색을 적용 했습니다.
- 동글동글 라운드 버튼 메인컬러, 회색 버전 컴포넌트화 했습니다 
[feat: Round, RoundDisabled button components](https://github.com/Z-P0P/ZPOP/commit/e6de41f31decdf5fc9fc9fa2af8c5b41054e9499)
- MeetingDetailResponse에 Getter 롬복 추가했습니다. hasParticipated 값도 잘 넘어오네요
[MeetingDetailResponse.java](https://github.com/Z-P0P/ZPOP/commit/85c048da41ddca1d81d420ccba7e97e8331c7a78)
- 상황에 맞는 모임 참여하기, 모집완료, 마감하기, 참여취소 버튼 렌더링을 구현했습니다
[feat: implement of meeting control-btn that changes for each situation](https://github.com/Z-P0P/ZPOP/commit/b7bd1156a3ab7a94fdfd19b6f163c92914a7f733)
- 모임 Detail.vue에 유효하지 않는 Id로 요청시 404 vue로 이동하게 구현했습니다
[feat: add 404 handle Detail.vue](https://github.com/Z-P0P/ZPOP/commit/dfec582309236bb3810e609a184475ac5cc9 …
> feat: detail article btn

- src/main/java/com/zpop/web/controller/MeetingController.java
- src/main/vue/src/api/meeting.js
- src/main/vue/src/components/meeting/article/Article.vue
- src/main/vue/src/components/meeting/article/ControlModal.vue
모임 참여 취소를 구현했읍니다
참여, 참여 취소후 모임 상세조회를 다시 요청해서 매번 조회수가 오르는데,
이걸 해결 해보려 참여자만 재조회하려했는데요
하고나서 보니 참여하기, 참여취소 등 컨트롤러 버튼도 처리해야하는게 까다로워서 일답 냅두었읍니다
> feat: 모임 참여 취소

- src/main/java/com/zpop/web/controller/MeetingController.java
- src/main/vue/src/api/meeting.js
- src/main/vue/src/components/comment/CommentList.vue
- src/main/vue/src/components/meeting/Participants.vue
- src/main/vue/src/components/meeting/article/Article.vue
- src/main/vue/src/components/meeting/article/ControlModal.vue
- src/main/vue/src/stores/meetingDetailStore.js
- src/main/vue/src/views/meeting/Detail.vue
[feat: meetingDetailStore](https://github.com/Z-P0P/ZPOP/commit/6e442fd8910d696e2d9809c049123822fd20ece7)
Detail.vue에서 모임 정보, 참여자 리스트, 댓글리스트에 대해 props으로 전달하고 있었는데, model 최신화 + 화면 재렌더링 하기가 껄끄러웠음
따라서 meetingDetail store 추가 하여 해결함
모임 정보, 참여자 리스트, 댓글 리스트에 반영하였음
모임 마감하기를 구현 함
> feat: 모임 마감하기 + 모임 상세 store

- src/main/vue/src/components/meeting/article/Article.vue
- src/main/vue/src/components/meeting/article/ControlModal.vue
- src/main/vue/src/stores/meetingDetailStore.js
- 모임 참여 취소후, 화면의 참여자 리스트를 재 렌더링하기위해 get detail api를 호출함
- 이는 매번 조회수가 오르는 문제가 있어서 수정함
https://github.com/Z-P0P/ZPOP/pull/149
> refactor: 모임 참여 취소

- src/main/vue/src/utils/RegisterForm.js
- src/main/vue/src/views/meeting/Register.vue
- 모임글 등록 시 입력값이 유효하지 않은 경우에도 정상 처리되는 모달로 전환되었는데, 해당 이슈를 해결하였음
입력값 검증 후 유효하지 않은 입력값이 확인되었으나, 정상 처리되는 모달로 전환되었음
입력값 검증 후 유효하지 않은 입력값이 확인되면 오류 모달을 띄우도록 수정함
- N/A
> [FIX] 모임글 등록 시 입력값이 유효하지 않은 경우에도 정상 처리되는 모달로 전환되는 이슈 해결

- src/main/vue/src/components/meeting/option-control/Region.vue
- 메인화면에서 지역옵션 선택 시 3개 이상 선택하는 경우 가장 마지막에 선택한 값이 무조건 사라지는 버그 수정함
- 조건문에서 지역옵션이 3개인 경우 마지막으로 선택된 지역옵션을 제거해버리고 선택된 지역옵션을 추가하는 로직을 넣지 않았음
- 상기 로직을 추가하였음
- N/A
> [FIX] 메인 조회화면에서 지역옵션 선택 시 3개 이상 고르는 경우 무조건 마지막 지역이 없어지는 버그 수정

- src/main/vue/src/components/modal/LoginModal.vue
- src/main/vue/src/router/index.js
- src/main/vue/src/views/LoginProc.vue
- src/main/vue/src/views/meeting/List.vue
- 로그인 기능을 개선했습니다
- 카카오 로그인 기능을 다시 추가했습니다.
- 기존에는 소셜로그인 리다이렉트 url이 아래와 같이 별도의 view로 있었는데, view 디자인이 따로 있는 것도 아니고 해서 그냥 메인 화면에 통합하는 것이 어떨까 의견드립니다.
- redirect url 이 수정이 안돼서 카카오 로그인이 안된 것 같습니다.
- loginProc.vue는 별도의 router-view가 아닌 메인화면의 component로 이동했습니다.
- 옮기고 나니 기존에 사용했던 /login/oauth/naver(또는 kakao)는 사용할 수 없어서 redirect url을 변경했습니다.
=> /?login=naver 나 /?login=kakao 로 redirect 하고자 합니다.
- 동일 router-view 내에서 push하는 것은 router.push 시 router guard의 beforeEnter 가 활성화되지 않는 것 같습니다. 따라서 router에 있던 redirectRouteAfterLogin 는 loginProc 기능의 일부로 옮겼습니다.
=> 로직을 그쪽으로 옮겨도 리다이렉트 기능은 잘 동작합니다.
수정 전
```js
function redirectRouteAfterLogin(to, from) {
const redirectRoute = localStorage.getItem("redirect-route");
if (from.path.includes("login/oauth") && redirectRoute) {
localStorage.removeItem("redirect-route"); …
```
> [FEAT, REFACTOR] 로그인 기능 개선 및 카카오 로그인 기능 수정

- src/main/vue/src/assets/css/component/select.css
- src/main/vue/src/components/header/Profile.vue
- src/main/vue/src/components/meeting/MeetingFormSelectInput.vue
- src/main/vue/src/components/meeting/MeetingFormSelectTextInput.vue
- src/main/vue/src/components/meeting/article/SelectModal.vue
- css 수정하면서 케밥 셀렉트 모달의 css 버그가 발생했음
- select box의 css로 인해 헤더 프로필 버튼에 margin-top이 적용되었음
- 헤더 프로필 버튼의 크기가 이미지 height보다 살작 더 커서 정렬이 맞지 않는 현상이 있었음
- class 추가 및 scoped style 적용
-select box에 적용된 margin-top을 제거하고, 개별 component (모임글 관련 컴포넌트) 에서 scoped style로 적용하도록 변경
-프로필 버튼의 height 크기 설정 (반응형 고려하여 32px => 40px로 설정)
- N/A
> [FIX] 모임글 상세보기의 Article.vue 에서 케밥 아이콘 클릭했을 때 css가 깨지는 현상 및 기타 CSS 수정

- src/main/resources/static/css/admin/style.css
- src/main/resources/static/css/tooltip.css
- src/main/resources/static/tooltip.html
- src/main/vue/src/assets/css/component/tooltip.css
- 초창기 html css 연습할 때 만들었던 툴팁 부활
- 아래의 예시 참고
```html
<body>
<div style="display:flex; flex-direction:column; justify-content: space-between;margin: 100px 50%; height: 400px">
<span class="list-status status-round status-incomplete tooltip">
TBD
<span class="tooltip-solid tooltip-solid-right">tooltip-solid-right</span>
</span>
<span class="list-status status-positive tooltip">
ACTIVE
<span class="tooltip-solid tooltip-solid-bottom">
tooltip-solid-bottom
</span>
</span>
<span class="list-status status-round status-positive">TRUE</span>
<span class="list-status status-round status-neutral tooltip">
REJECTED
<span class="tooltip-solid tooltip-solid-left">
tooltip-solid-left
</span>
</span>
<span class="list-status status-round status-negative">FALSE</span>
<span class="list-status …
```
> [FEAT] 툴팁추가

- src/main/java/com/zpop/web/utils/ElapsedTimeCalculator.java
- src/main/vue/src/assets/css/meeting/component/comment.css
- src/main/vue/src/views/meeting/Detail.vue
- 모임 상세페이지 데스크탑 사이즈를 740이상으로 정상화
- 댓글 간의 수직간격에 27px 마진을 줌
- 댓글 작성시간의 '방금'을 '방금 전'으로 수정
> [fix] detail page css

- src/main/java/com/zpop/web/controller/LoginController.java
- src/main/java/com/zpop/web/controller/RegisterController.java
- src/main/java/com/zpop/web/entity/Member.java
- src/main/java/com/zpop/web/entity/NicknameLog.java
- src/main/java/com/zpop/web/global/exception/ExceptionReason.java
- src/main/java/com/zpop/web/service/RegisterService.java
- src/main/resources/mapper/MemberDaoMapper.xml
- src/main/resources/static/css/button.css
- src/main/resources/static/css/form.css
- src/main/resources/templates/meeting/detail.html
- src/main/vue/src/assets/css/button.css
- src/main/vue/src/assets/css/form.css
- src/main/vue/src/components/button/RoundDisabled.vue
- src/main/vue/src/components/modal/NicknameRegister.vue
- src/main/vue/src/views/LoginProc.vue
- src/main/vue/src/views/meeting/List.vue
- 사용자 최초 소셜로그인 시 닉네임 설정 및 계정 등록하는 기능 추가하였음
- 기존에는 순수 js로만 구현되어있었습니다.
- 기존에는 동일 social id로 계정 추가할 때 별도의 처리 없이 등록이 가능했습니다.
- vue.js로 프론트쪽 구현했습니다.
- 닉네임 설정이 되면 memberStore의 isAuthenciated()를 호출해서 별도의 리다이렉션이나 refresh없이 header를 갱신할 수 있도록 했습니다.
- 찬우님이 만드신 CustomException을 사용해서 예외처리했습니다.
- 로그인모달과 계정설정 모달의 포멧이 공유되는데, slot을 이용해서 컴포넌트화하는 것이 좋을 것 같습니다.
- 만약에 탈퇴기능 구현된다면, social id 이미 등록되어있을 때 예외 발생하는 로직은 추가적으로 수정 필요합니다.
> [FEAT] 최초 소셜로그인 시 사용자 닉네임 등록기능

- src/main/vue/src/components/meeting/option-control/Region.vue
- src/main/vue/src/main.js
- 지역카테고리 옵션이 모바일에서 간헐적으로 사라지지 않는 현상을 수정했습니다.
- 모바일 화면에서 모임글을 클릭하여 상세글보기를 한 뒤 다시 돌아왔을 때 지역카테고리옵션이 보이는 버그가 있었습니다.
- 지역옵션 선택 색상이 true-blue로 되어있었습니다.
- 확인 결과 region-category에서 select.css를 import하고 있었는데, 이 파일을 main.js에 옮기고 scoped를 주니 개선되었습니다.
- 지역옵션 선택 색상을 main-color로 변경했습니다.
> [FIX]모바일화면에서 간헐적으로 지역카테고리 옵션이 보이는 버그 수정 & 지역옵션선택 색상변경 (main-color)

- src/main/java/com/zpop/web/controller/LoginController.java
- src/main/java/com/zpop/web/controller/MemberController.java
- src/main/java/com/zpop/web/dao/ParticipationDao.java
- src/main/java/com/zpop/web/dto/ProfileResponse.java
- src/main/java/com/zpop/web/global/exception/ExceptionReason.java
- src/main/java/com/zpop/web/service/DefalutMemberService.java
- src/main/java/com/zpop/web/service/MemberService.java
- src/main/resources/mapper/ParticipationDaoMapper.xml
- src/main/vue/src/components/meeting/MemberProfile.vue
- 의미에 맞게 변수명, 함수명 수정
- 함수 위치 수정
- DAO 쿼리 사용 목적에 맞게 수정
- 모임 참여횟수 카운트 로직 수정
다음은 추후 구현할 사항입니다
- `내보내기` 렌더링 여부
- `탈퇴회원`
- 프사 유무
> refactor: 회원 프로필 조회

- src/main/vue/src/api/comment.js
- src/main/vue/src/components/comment/Comment.vue
- src/main/vue/src/components/comment/CommentList.vue
- src/main/vue/src/components/comment/CommentModal.vue
- src/main/vue/src/components/comment/InputBox.vue
- src/main/vue/src/components/comment/Reply.vue
- src/main/vue/src/components/comment/ReplyList.vue
- src/main/vue/src/components/comment/SelectModal.vue
- 댓글/답글 수정/삭제 케밥기능 구현 완료
- 비로그인시 댓글/답글 각종 기능 차단하고 로그인화면으로 보냄
- 비로그인시 댓글리스트와 답글 리스트만 볼 수 있도록 허용
- 모든 AJAX콜을 try-catch로 전환하여 예외처리보강(alert대신 모달로 안내함)
- 댓글/답글의 내용이 비어있는 상태에서 등록버튼을 누를때 (귀찮아서) alert경고창이 뜨도록한 것을 추후 모달로 변경
- 댓글 삭제시 달려있는 답글을 그대로 두고 댓글만 삭제하고 내용을 (삭제됨)으로 표시할지 여부 결정
> [FEAT] comment & reply kebob select menu 완료

- src/main/java/com/zpop/web/controller/admin/HomeController.java
- src/main/java/com/zpop/web/controller/admin/MeetingController.java
- src/main/java/com/zpop/web/controller/admin/MemberController.java
- src/main/java/com/zpop/web/dao/AgeRangeDao.java
- src/main/java/com/zpop/web/dao/MeetingDao.java
- src/main/java/com/zpop/web/dao/MemberDao.java
- src/main/java/com/zpop/web/dto/admin/OptionCountDto.java
- src/main/java/com/zpop/web/dto/admin/meeting/CountPerDateDto.java
- src/main/java/com/zpop/web/security/SecurityConfig.java
- src/main/java/com/zpop/web/service/admin/AdminHomeService.java
- src/main/java/com/zpop/web/service/admin/AdminMeetingService.java
- src/main/java/com/zpop/web/service/admin/AdminMemberService.java
- src/main/java/com/zpop/web/service/admin/DeafultAdminMemberService.java
- src/main/java/com/zpop/web/service/admin/DefaultAdminHomeService.java
- src/main/java/com/zpop/web/service/admin/DefaultAdminMeetingService.java
- src/main/resources/mapper/AgeRangeDaoMapper.xml
- src/main/resources/mapper/ContactTypeDaoMapper.xml
- src/main/resources/mapper/MeetingDaoMapper.xml
- src/main/resources/mapper/MemberDaoMapper.xml
- src/main/vue/package-lock.json
- src/main/vue/package.json
- src/main/vue/src/assets/css/deco.css
- src/main/vue/src/router/admin.js
- src/main/vue/src/views/admin/Home/Home.vue
- <img width="968" alt="image" src="https://user-images.githubusercontent.com/102606939/215395493-11e7b6b9-7700-4861-ac3b-48a6731565fc.png">
- 관리자 대시보드 화면이 추가되었습니다.
- 다음과 같은 내용을 표시합니다.
1. 전체회원수, 전체모임수, 어제가입한 회원수 어제 개설된 모임수 표시
2. 카테고리 별 모임 수 표시
3. 지역 별 모임 수 표시
4. 연령대 별 모임 수 표시
5. 연락방법 별 모임 수 표시
6. 모집 중 / 마감된 모임 수 표시
7. 성별 모임 수
8. 모임 개설 수 추이 (30일 이내)
9. 회원 가입자 수 추이 (30일 이내)
- vue-chart-js 와 vue-chart-datalabels 관련 의존성이 추가되었습니다.
> feat: add admin dashboard

- src/main/java/com/zpop/web/controller/MeetingController.java
- src/main/java/com/zpop/web/dto/KickDto.java
- src/main/java/com/zpop/web/global/exception/ExceptionReason.java
- src/main/java/com/zpop/web/service/DefaultMeetingService.java
- src/main/java/com/zpop/web/service/MeetingService.java
- src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java
-  백엔드 재구현입니다
- 지운 `TempMeetingController`에 있던 매핑을 `MeetingController`에 추가했읍니다
- 탈퇴 회원도 내보낼 수 있게 기획에 따라 수정했습니다
- 인자에 시큐리티를 반영(Member member -> int hostId)했습니다
> feat: 모임 내보내기 백엔드

- src/main/vue/src/components/meeting/Thumbnail.vue
- 모임 썸네일에 마우스를 올릴 때, 클릭할 때 우아한 그림자를 적용했습니다
> style: 모임 썸네일 hover & active css

- src/main/java/com/zpop/web/controller/MemberController.java
- src/main/java/com/zpop/web/dao/MemberDao.java
- src/main/java/com/zpop/web/entity/ProfileFile.java
- src/main/java/com/zpop/web/service/DefalutMemberService.java
- src/main/java/com/zpop/web/service/MemberService.java
- src/main/java/com/zpop/web/utils/FileNameGenerator.java
- src/main/resources/mapper/MemberDaoMapper.xml
- src/main/vue/src/assets/css/component/header.css
- src/main/vue/src/components/header/Profile.vue
- src/main/vue/src/components/member/ProfileEdit.vue
- 마이프로필에서 프로필 사진 업데이트 시 사용자 프로필이 업데이트되지 않는 부분을 수정하였습니다.
- 프로필 사진 업데이트 시 한글파일을 업로드하거나, 또는 파일명이 중복되는 것을 올릴 때 발생할 수 있는 부분을 수정하였습니다.
- 사용자가 자신의 프로필 사진을 업데이트할 때 profileFile이라는 테이블에 프로필 사진이 정상적으로 업로드 되나, 프로필 개시자의 memberId가 반영되지 않는 부분과 member테이블에서 profileImagePath가 업데이트되지 않는 문제가 있었음
- 프로필 사진 업데이트 시 파일명에 한글이 들어가는 경우 불러오는데 실패하고,  파일명이 중복된 이미지를 올릴 경우 덮어써지는 문제가 있음.
- memberId를 userDetails에서 받아 profileFile테이블을 업데이트하도록 변경
- member테이블을 업데이트하도록 코드 추가
- 이미지 명은 ZPOP_PROFILE_'YYYY_MM_DD_HH_mm_SS_SSS' 로 업데이트 되도록 수정 (이로 인한 테이블 제약조건 수정 name의 VARCHAR(30) => VARCHAR(40)
- 프로필 업데이트 성공 시 백엔드에서 profileFile을 response로 보내고, 거기에 있는 파일명을 이용해 헤더 이미지를 수정하도록 변경
- N/A
> [FIX] 마이 프로필에서 프로필 사진 업데이트 시 사용자 프로필이 업데이트되지 않는 부분 수정

- src/main/vue/src/components/modal/NicknameRegister.vue
- 닉네임 설정 화면에서 닉네임이 공란일 때 로그인 설정버튼을 누르면 넘어가는 버그를 수정했음
- 닉네임 설정화면에서 닉네임이 공란일 때 예외가 발생하지 않아 다음 페이지로 넘어가는 버그가 있었음.
- 넘어가긴 해도 실제로 db에 회원등록으로 이어지지는 않았음
- 닉네임 설정화면에서 닉네임이 공란이면 예외가 발생하도록 코드를 수정
```js
const validateNickname = () => {
// 생략
if (nickname.value.length === 0) {
throw new Error('닉네임은 공백이 될 수 없어요!');
}
if (nickname.value.length > maxNicknameLength){
throw new Error('닉네임은 10글자 이하로 입력해주세요!');
}
// 생략
```
- N/A
> fix: 닉네임 설정 화면에서 닉네임이 공란일 때 로그인 설정버튼을 누르면 넘어가는 버그 수정

- src/main/java/com/zpop/web/controller/ReplyController.java
- src/main/java/com/zpop/web/dto/CommentResponse.java
- src/main/java/com/zpop/web/entity/comment/CommentView.java
- src/main/java/com/zpop/web/service/DefaultMeetingService.java
- src/main/vue/src/assets/css/meeting/component/profile-box.css
- src/main/vue/src/components/comment/Comment.vue
- src/main/vue/src/components/comment/Reply.vue
- src/main/vue/src/components/meeting/article/Article.vue
-<img width="421" alt="image" src="https://user-images.githubusercontent.com/102606939/216010126-d7e15056-3a1a-436e-967c-ebe8aff95917.png">
- 댓글, 대댓글에 작성자 프로필이 기본 프로필로만 보이는 이슈가 있었음
- <span>태그에 background-image 속성으로 기본 프로필(회색)을 보여주는 상황이라, <img> 태그를 추가할 필요가 있었음
- db에서 groupId를 통해 commentView를 받아올 때, dto의 속성 중 'profileImgPath' 가 db의 컬럼명인 'profileImagePath' 와 맞지 않아 db에서는 조회가 돼도 dto에 값을 넘겨주지 못하는 이슈가 있었음
- <img> 태그를 안에 넣고, 프로필 이미지 경로를 :src에 바인딩해주었음 (& 관련 css 수정)
- db의 member 컬럼명과 동일한 profileImagePath로 commentView를 수정하였고, getter와 setter 및 생성자를 지우고 lombok 적용하였음
- N/A
> fix: 작성된 댓글에서 댓글 작성자의 프로필 이미지가 보이지 않는 버그 수정

- src/main/vue/src/assets/css/meeting/component/profile-box.css
- src/main/vue/src/components/modal/Default.vue
- 모달의 wrapper에 z index가 없어서 998로 지정하여 모달의 999바로 하단에 위치하게 함으로써 다른 화면내 다른요소들과의 배경색 충돌을 방지함.
> fix: default modal z-index, comment kebob bg color

- src/main/java/com/zpop/web/service/DefalutMemberService.java
* 닉네임 빈문자열 입력후 프로필 저장하면 닉네임이 빈문자열로 바뀌던 버그 수정
> fix: 닉네임 입력 없이 프로필 수정 되던 현상 수정
